name: Build

on:
  workflow_dispatch:
    inputs:
      update_manifest:
        default: false
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run maximize-build-space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install repo
      run: |
        wget https://storage.googleapis.com/git-repo-downloads/repo -O /usr/local/bin/repo
        chmod +x /usr/local/bin/repo

    - name: Sync androidx-main
      run: |
        mkdir androidx-main
        cd androidx-main
        repo init -u https://android.googlesource.com/platform/manifest -b androidx-main --depth=1
        if [[ "${{ inputs.update_manifest }}" = "true" ]]; then
          repo sync -j16
        else
          repo sync -m $GITHUB_WORKSPACE/manifest.xml -j16
        fi
        repo manifest -r > $GITHUB_WORKSPACE/manifest.xml

    - name: Apply patches
      working-directory: androidx-main
      run: |
        pushd frameworks/support
        git am $GITHUB_WORKSPACE/patches/2155293/*
        git fetch https://android.googlesource.com/platform/frameworks/support refs/changes/75/2188775/7 && git cherry-pick FETCH_HEAD~5..FETCH_HEAD
        git am $GITHUB_WORKSPACE/patches/0001-Add-hacky-way-for-us-to-make-certain-camera-IDs-back.patch
        popd

    - name: Build
      working-directory: androidx-main/frameworks/support
      run: |
        rm -rf $GITHUB_WORKSPACE/.m2 || true
        ./gradlew \
          -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2 \
          camera:camera-core:publishToMavenLocal \
          camera:camera-camera2:publishToMavenLocal \
          camera:camera-lifecycle:publishToMavenLocal \
          camera:camera-video:publishToMavenLocal \
          camera:camera-view:publishToMavenLocal \
          camera:camera-mlkit-vision:publishToMavenLocal \
          camera:camera-extensions:publishToMavenLocal

    - name: Commit changes
      run: |
        git add .m2
        git commit -m "Publish maven artifacts" || true
        git add manifest.xml
        git commit -m "Update manifest" || true

    - name: Push changes to repo
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
